name: Build Thunder on Linux

on:
  pull_request:
    branches: ["master"]
  workflow_call:
 
env:
 branch: ${{ github.head_ref || github.ref_name }}
 
jobs:
  Thunder:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release, MinSizeRel]
    
    name: Build type - ${{matrix.build_type}}
    steps:
    - name: First regex ThunderTools
      id: regex1
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '\[DependsOn:ThunderTools=.+\]'
        regex_flags: 'gim'
        search_string: ${{github.event.pull_request.body}}
    
    - name: Second regex ThunderTools
      id: regex2
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '=.+\]'
        regex_flags: 'gim'
        search_string: ${{steps.regex1.outputs.first_match}}
    
    - name: Third regex ThunderTools
      id: regex3
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '[^=].+[^\]]'
        regex_flags: 'gim'
        search_string: ${{steps.regex2.outputs.first_match}}

    - name: Checkout Thunder - default
      if: ${{ !contains(github.event.pull_request.body, '[DependsOnThunder]') }}
      uses: actions/checkout@v3
      with:
        path: Thunder
        repository: rdkcentral/Thunder
        
    - name: Checkout Thunder - ${{env.branch}}
      if: contains(github.event.pull_request.body, '[DependsOnThunder]')
      uses: actions/checkout@v3
      with:
        path: Thunder
        repository: rdkcentral/Thunder
        ref: ${{env.branch}}
        
    - name: Checkout ThunderTools - default
      if: ${{ !contains(github.event.pull_request.body, 'DependsOn') }}
      uses: actions/checkout@v3
      with:
        path: ThunderTools
        repository: rdkcentral/ThunderTools

# CHANGE TO RDKCENTRAL
    - name: Checkout ThunderTools - ${{env.branch}}
      if: contains(github.event.pull_request.body, 'DependsOn')
      uses: actions/checkout@v3
      with:
        path: ThunderTools
        repository: VeithMetro/ThunderTools
        ref: ${{steps.regex3.outputs.first_match}}

    - name: Install necessary packages
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 10
        command: |
          sudo gem install apt-spy2
          sudo apt-spy2 fix --commit --launchpad --country=US
          sudo apt-get update
          sudo apt install python3-pip
          pip install jsonref
          sudo apt install build-essential cmake ninja-build libusb-1.0-0-dev zlib1g-dev libssl-dev
        
    - name: Install generators
      run: |
        cmake -G Ninja -S ThunderTools -B ${{matrix.build_type}}/build/ThunderTools \
        -DCMAKE_INSTALL_PREFIX=${{matrix.build_type}}/install/usr
        cmake --build ${{matrix.build_type}}/build/ThunderTools --target install
        
    - name: Build Thunder
      run: |
        cmake -G Ninja -S Thunder -B ${{matrix.build_type}}/build/Thunder \
        -DBINDING="127.0.0.1" \
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
        -DCMAKE_INSTALL_PREFIX="${{matrix.build_type}}/install/usr" \
        -DCMAKE_MODULE_PATH="${PWD}/${{matrix.build_type}}/install/usr/include/WPEFramework/Modules" \
        -DDATA_PATH="${PWD}/${{matrix.build_type}}/install/usr/share/WPEFramework" \
        -DPERSISTENT_PATH="${PWD}/${{matrix.build_type}}/install/var/wpeframework" \
        -DPORT="55555" \
        -DPROXYSTUB_PATH="${PWD}/${{matrix.build_type}}/install/usr/lib/wpeframework/proxystubs" \
        -DSYSTEM_PATH="${PWD}/${{matrix.build_type}}/install/usr/lib/wpeframework/plugins" \
        -DVOLATILE_PATH="tmp"
        cmake --build ${{matrix.build_type}}/build/Thunder --target install
    
    - name: Tar files
      run: tar -czvf ${{matrix.build_type}}.tar.gz ${{matrix.build_type}}
    
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: Thunder-${{matrix.build_type}}-artifact
        path: ${{matrix.build_type}}.tar.gz
