name: CMake Thunder

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release, MinSizeRel]
    
    name: Build type - ${{matrix.build_type}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: Thunder
        repository: VeithMetro/Thunder

    - name: Install necessary packages
      run: |
        sudo apt install build-essential cmake ninja-build libusb-1.0-0-dev zlib1g-dev libssl-dev python3-pip
        pip install jsonref
        
    - name: Install generators
      run: |
        cmake -G Ninja -S Tools -B Thunder/build/tools -DCMAKE_INSTALL_PREFIX=Thunder/install/usr
        cmake --build Thunder/build/tools --target install
        
    - name: Build Thunder
      run: |
        cmake -G Ninja -S Thunder -B Thunder/build/thunder \
        -DBINDING="127.0.0.1" \
        -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
        -DCMAKE_INSTALL_PREFIX="Thunder/install/usr" \
        -DCMAKE_MODULE_PATH="${PWD}/Thunder/install/usr/include/WPEFramework/Modules" \
        -DDATA_PATH="${PWD}/Thunder/install/usr/share/WPEFramework" \
        -DMESSAGING=ON \
        -DPERSISTENT_PATH="${PWD}/Thunder/install/var/wpeframework" \
        -DPORT="55555" \
        -DPROXYSTUB_PATH="${PWD}/Thunder/install/usr/lib/wpeframework/proxystubs" \
        -DSYSTEM_PATH="${PWD}/Thunder/install/usr/lib/wpeframework/plugins" \
        -DTRACING=OFF \
        -DVOLATILE_PATH="Thunder/tmp"
        cmake --build Thunder/build/thunder --target install
