name: CMake Thunder

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install necessary packages
      run: |
        sudo apt install build-essential cmake ninja-build libusb-1.0-0-dev zlib1g-dev libssl-dev python3-pip
        pip install jsonref
        
    - name: Install generators
      run: |
        cmake -G Ninja -S Tools -B build/tools -DCMAKE_INSTALL_PREFIX=install/usr
        cmake --build build/tools --target install
        
    - name: Build Thunder
      run: |
        cmake -G Ninja -S . -B build/thunder \
        -DCMAKE_INSTALL_PREFIX="install/usr" \
        -DCMAKE_MODULE_PATH="${PWD}/install/usr/include/WPEFramework/Modules" \
        -DTRACING=OFF \
        -DMESSAGING=ON \
        -DCMAKE_BUILD_TYPE=Debug \
        -DPERSISTENT_PATH="${PWD}/install/var/wpeframework" \
        -DVOLATILE_PATH="/tmp" \
        -DDATA_PATH="${PWD}/install/usr/share/WPEFramework" \
        -DSYSTEM_PATH="${PWD}/install/usr/lib/wpeframework/plugins" \
        -DPROXYSTUB_PATH="${PWD}/install/usr/lib/wpeframework/proxystubs" \
        -DPORT="55555" \
        -DBINDING="127.0.0.1"
        cmake --build build/thunder --target install
